// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXMXxjboH4LIlqIvk0AL0g0cvXADD4yw',
    appId: '1:630510501422:web:7044106037ce3979cd69bf',
    messagingSenderId: '630510501422',
    projectId: 'location-tracker-b4266',
    authDomain: 'location-tracker-b4266.firebaseapp.com',
    storageBucket: 'location-tracker-b4266.appspot.com',
    measurementId: 'G-P7W51X0658',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfCQYNR-fDLGy6wf3O4BDvZjBiJOktEtk',
    appId: '1:630510501422:android:2260efd671213914cd69bf',
    messagingSenderId: '630510501422',
    projectId: 'location-tracker-b4266',
    storageBucket: 'location-tracker-b4266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshlY_b08VYR6xrQjDnx12_GxVfcgqsrE',
    appId: '1:630510501422:ios:28f884bd2ad7bb2ecd69bf',
    messagingSenderId: '630510501422',
    projectId: 'location-tracker-b4266',
    storageBucket: 'location-tracker-b4266.appspot.com',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCshlY_b08VYR6xrQjDnx12_GxVfcgqsrE',
    appId: '1:630510501422:ios:28f884bd2ad7bb2ecd69bf',
    messagingSenderId: '630510501422',
    projectId: 'location-tracker-b4266',
    storageBucket: 'location-tracker-b4266.appspot.com',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCXMXxjboH4LIlqIvk0AL0g0cvXADD4yw',
    appId: '1:630510501422:web:c3fa3faf0de96062cd69bf',
    messagingSenderId: '630510501422',
    projectId: 'location-tracker-b4266',
    authDomain: 'location-tracker-b4266.firebaseapp.com',
    storageBucket: 'location-tracker-b4266.appspot.com',
    measurementId: 'G-FYS8CHPR64',
  );
}
